import Vue from 'vue'

import './styles/quasar.styl'
//import iconSet from 'quasar/icon-set/fontawesome-v5.js'
import '@quasar/extras/fontawesome-v5/fontawesome-v5.css'
import '@quasar/extras/roboto-font/roboto-font.css'
import '@quasar/extras/material-icons/material-icons.css'

import {
  Quasar, 
  QLayout,
  QHeader,
  QFooter,
  QDrawer,
  QPageContainer,
  QPage,
  QToolbar,
  QToolbarTitle,
  QBtn,
  QIcon,
  QList,
  QItem,
  QItemSection,
  QItemLabel,
  QScrollArea,
  QSeparator,
  Ripple,
  QRadio,
  QCard,
  QCardSection,
  QCardActions,
  QInput,
  QField,
  QAvatar,
  QImg,
  QSpace,
  QBanner,
  QPopupProxy,
  ClosePopup,
  QBadge,
  AppFullscreen,
  //CloseOverlay,
  QTabs,
  //QItemMain,
  QTabPanels,
  QTabPanel,
  Notify,
  Dialog,
  QSplitter,
  QTab,
  QChip,
  QToggle,
  QCheckbox,
  QExpansionItem,
  QTable,
  QTh,
  QTr,
  QTd,
  QBtnGroup,
  QDialog,
  QBtnToggle,
  QForm,
  QSelect,
  QUploader,
  QCircularProgress,
  QDate,
  Platform,
} from 'quasar'

Vue.use(Quasar, {
  config: {},
  components: {
    QLayout,
    QHeader,
    QFooter,
    QDrawer,
    QPageContainer,
    QPage,
    QToolbar,
    QToolbarTitle,
    QBtn,
    QIcon,
    QList,
    QItem,
    QItemSection,
    QItemLabel,
    QScrollArea,
    QSeparator,
    QRadio,
    QCard,
    QCardSection,
    QCardActions,
    QInput,
    QField,
    QAvatar,
    QImg,
    QSpace,
    QBanner,
    QPopupProxy,
    QBadge,
    QTabs,
    //QItemMain,
    QTabPanels,
    QTabPanel,
    QSplitter,
    QTab,
    QChip,
    QToggle,
    QCheckbox,
    QExpansionItem,
    QTable,
    QTh,
    QTr,
    QTd,
    QBtnGroup,
    QDialog,
    QBtnToggle,
    QForm,
    QSelect,
    QUploader,
    QCircularProgress,
    QDate,
  },
  directives: {
    //CloseOverlay,
    Ripple,
    ClosePopup,
  },
  plugins: {
    AppFullscreen,
    Notify, Dialog,
    Platform  
  },
  //iconSet: iconSet
 })